In [5]:
import pandas as pd

In [9]:
import csv
from sklearn.preprocessing import LabelEncoder
np_iris = None
pd_data = None
with open('iris.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    raw_data = [row for row in reader]
  

    pd_data = pd.DataFrame.from_records(raw_data)

    label_encoder = LabelEncoder()

    print(label_encoder.fit_transform(["A", "A", "C", "B", "C", "A", "B"]))

    np_iris = pd_data.to_numpy()

[0 0 2 1 2 0 1]


In [10]:
print(type(np_iris))
print(np_iris)

print(pd_data["Species"])




<class 'numpy.ndarray'>
[['5.1' '3.5' '1.4' '0.2' 'setosa']
 ['4.9' '3' '1.4' '0.2' 'setosa']
 ['4.7' '3.2' '1.3' '0.2' 'setosa']
 ['4.6' '3.1' '1.5' '0.2' 'setosa']
 ['5' '3.6' '1.4' '0.2' 'setosa']
 ['5.4' '3.9' '1.7' '0.4' 'setosa']
 ['4.6' '3.4' '1.4' '0.3' 'setosa']
 ['5' '3.4' '1.5' '0.2' 'setosa']
 ['4.4' '2.9' '1.4' '0.2' 'setosa']
 ['4.9' '3.1' '1.5' '0.1' 'setosa']
 ['5.4' '3.7' '1.5' '0.2' 'setosa']
 ['4.8' '3.4' '1.6' '0.2' 'setosa']
 ['4.8' '3' '1.4' '0.1' 'setosa']
 ['4.3' '3' '1.1' '0.1' 'setosa']
 ['5.8' '4' '1.2' '0.2' 'setosa']
 ['5.7' '4.4' '1.5' '0.4' 'setosa']
 ['5.4' '3.9' '1.3' '0.4' 'setosa']
 ['5.1' '3.5' '1.4' '0.3' 'setosa']
 ['5.7' '3.8' '1.7' '0.3' 'setosa']
 ['5.1' '3.8' '1.5' '0.3' 'setosa']
 ['5.4' '3.4' '1.7' '0.2' 'setosa']
 ['5.1' '3.7' '1.5' '0.4' 'setosa']
 ['4.6' '3.6' '1' '0.2' 'setosa']
 ['5.1' '3.3' '1.7' '0.5' 'setosa']
 ['4.8' '3.4' '1.9' '0.2' 'setosa']
 ['5' '3' '1.6' '0.2' 'setosa']
 ['5' '3.4' '1.6' '0.4' 'setosa']
 ['5.2' '3.5' '1.5' '0.2

In [1]:
# import pandas as pd
# import numpy as np

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

print(label_encoder.fit_transform(["A", "A", "C", "B", "C", "A", "B"]))

[0 0 2 1 2 0 1]


In [11]:
import numpy as np
from sklearn.preprocessing import StandardScaler

raw_data = [
    [1,3,5],
    [2,1,1],
    [1,3,1],
    [0,3,5],
]

np_data = np.array(raw_data)

print(np_data)
 

x = np_data[:3]

#Create a scaler model that is fit on the input data.
scaler = StandardScaler().fit(x)

#Scale the numeric feature variables
x_scaled = scaler.transform(x)


print(x, x_scaled)

[[1 3 5]
 [2 1 1]
 [1 3 1]
 [0 3 5]]
[[1 3 5]
 [2 1 1]
 [1 3 1]] [[-0.70710678  0.70710678  1.41421356]
 [ 1.41421356 -1.41421356 -0.70710678]
 [-0.70710678  0.70710678 -0.70710678]]


In [29]:
d=[1, 3, 5]
s=sum(d)
l=len(d)
avg = s/l
s2sum = sum([x**2 for x in d])
stddev = (s**2 - s2sum)**0.5

scaled = [(s - avg)/stddev for s in d]

 
print(d, scaled)

[1, 3, 5] [-0.29488391230979427, 0.0, 0.29488391230979427]


In [21]:
sum([-0.70710678,  0.70710678,  1.41421356])

1.41421356